Repository MarchTue/ReUse, pull requests merged in 2025-07, with the labels that each got.

#37 [BE]Fix #36 api 경로 수정
  Backend/auth/src/main/java/marchtue/reuse/auth/presentation/AuthContoller.java
  Backend/trade/src/main/java/marchtue/reuse/trade/presentation/CategoryController.java
  Backend/user/src/main/java/marchtue/reuse/user/presentation/UserController.java
Labels: BE

#49 [BE]Feat : #47 trade service security 적용
  Backend/trade/build.gradle
  Backend/trade/src/main/java/marchtue/reuse/trade/application/service/CategoryService.java
  Backend/trade/src/main/java/marchtue/reuse/trade/infrastructure/jpa/JpaCategoryRepository.java
  Backend/trade/src/main/java/marchtue/reuse/trade/infrastructure/jpa/JpaFavPostRepository.java
  Backend/trade/src/main/java/marchtue/reuse/trade/infrastructure/jpa/JpaPostImageRepository.java
  Backend/trade/src/main/java/marchtue/reuse/trade/infrastructure/jpa/JpaProposalRepository.java
  Backend/trade/src/main/java/marchtue/reuse/trade/infrastructure/jpa/JpaReviewRepository.java
  Backend/trade/src/main/java/marchtue/reuse/trade/infrastructure/jpa/JpaShippingLogRepository.java
  Backend/trade/src/main/java/marchtue/reuse/trade/infrastructure/jpa/JpaTradeRepository.java
  Backend/trade/src/main/java/marchtue/reuse/trade/infrastructure/security/JwtAuthenticationFilter.java
  Backend/trade/src/main/java/marchtue/reuse/trade/infrastructure/security/SecurityConfig.java
  Backend/trade/src/main/java/marchtue/reuse/trade/presentation/CategoryController.java
  Backend/user/src/main/java/marchtue/reuse/user/application/service/UserService.java
  Backend/user/src/main/java/marchtue/reuse/user/presentation/UserController.java
Labels: BE, Refactor

#50 [BE] Feat: #40 게시글 작성 및 목록, 단건 조회
  Backend/auth/src/main/java/marchtue/reuse/auth/application/client/UserClient.java
  Backend/trade/src/main/java/marchtue/reuse/trade/application/client/UserClient.java
  Backend/trade/src/main/java/marchtue/reuse/trade/application/client/UserClientImpl.java
  Backend/trade/src/main/java/marchtue/reuse/trade/application/dto/request/CreatePostRequest.java
  Backend/trade/src/main/java/marchtue/reuse/trade/application/dto/response/CreatePostResponse.java
  Backend/trade/src/main/java/marchtue/reuse/trade/application/dto/response/ReadPostListResponse.java
  Backend/trade/src/main/java/marchtue/reuse/trade/application/dto/response/ReadPostResponse.java
  Backend/trade/src/main/java/marchtue/reuse/trade/application/dto/response/ReadProductResponse.java
  Backend/trade/src/main/java/marchtue/reuse/trade/application/dto/response/ReadSellerResponse.java
  Backend/trade/src/main/java/marchtue/reuse/trade/application/dto/response/UserSimpleInfoResponse.java
  Backend/trade/src/main/java/marchtue/reuse/trade/application/service/CategoryService.java
  Backend/trade/src/main/java/marchtue/reuse/trade/application/service/PostService.java
  Backend/trade/src/main/java/marchtue/reuse/trade/domain/model/Post.java
  Backend/trade/src/main/java/marchtue/reuse/trade/domain/model/PostImage.java
  Backend/trade/src/main/java/marchtue/reuse/trade/domain/repository/FavPostRepository.java
  Backend/trade/src/main/java/marchtue/reuse/trade/domain/repository/PostImageRepository.java
  Backend/trade/src/main/java/marchtue/reuse/trade/domain/repository/PostRepository.java
  Backend/trade/src/main/java/marchtue/reuse/trade/exception/ErrorCode.java
  Backend/trade/src/main/java/marchtue/reuse/trade/global/dto/ApiResponse.java
  Backend/trade/src/main/java/marchtue/reuse/trade/global/util/RequestUtil.java
  Backend/trade/src/main/java/marchtue/reuse/trade/global/util/RestTemplateConfig.java
  Backend/trade/src/main/java/marchtue/reuse/trade/infrastructure/jpa/JpaPostRepository.java
  Backend/trade/src/main/java/marchtue/reuse/trade/presentation/PostController.java
  Backend/user/src/main/java/marchtue/reuse/user/application/dto/response/ReadSellerResponse.java
  Backend/user/src/main/java/marchtue/reuse/user/application/dto/response/UserSimpleInfoResponse.java
  Backend/user/src/main/java/marchtue/reuse/user/application/service/UserRatingService.java
  Backend/user/src/main/java/marchtue/reuse/user/application/service/UserService.java
  Backend/user/src/main/java/marchtue/reuse/user/global/dto/ApiResponse.java
  Backend/user/src/main/java/marchtue/reuse/user/infrastructure/security/SecurityConfig.java
  Backend/user/src/main/java/marchtue/reuse/user/presentation/UserInternalController.java
Labels: Feat, BE

#54 [FE] Docs: #53 버전 관리 문서 중간 작업
  reuse-app/README.md
  reuse-app/doc/version_0.1.md
  reuse-app/doc/version_0.3.md
  reuse-app/doc/version_0.4.md
  reuse-app/doc/version_0.md
  reuse-app/package.json
Labels: FE

#56 [FE]Setup #55: 프론트엔드 CHANGELOG 자동화
  reuse-app/CHANGELOG.md
  reuse-app/README.md
  reuse-app/changelog-gen.js
  reuse-app/package-lock.json
  reuse-app/package.json
  reuse-app/release.sh
Labels: FE

#57 [BE]Feat #40: 게시글 상세 조회
  Backend/trade/src/main/java/marchtue/reuse/trade/application/client/UserClient.java
  Backend/trade/src/main/java/marchtue/reuse/trade/application/client/UserClientImpl.java
  Backend/trade/src/main/java/marchtue/reuse/trade/application/dto/response/BuyerInfoResponse.java
  Backend/trade/src/main/java/marchtue/reuse/trade/application/dto/response/InTradingPostResponse.java
  Backend/trade/src/main/java/marchtue/reuse/trade/application/dto/response/InprogressPostResponse.java
  Backend/trade/src/main/java/marchtue/reuse/trade/application/dto/response/ProposalListResponse.java
  Backend/trade/src/main/java/marchtue/reuse/trade/application/service/PostService.java
  Backend/trade/src/main/java/marchtue/reuse/trade/domain/repository/ProposalRepository.java
Labels: Feat, BE

#59 [BE]Feat #40: 게시글 상세 조회
  Backend/trade/src/main/java/marchtue/reuse/trade/application/dto/response/InternalBuyerInfoResponse.java
Labels: Feat, BE

#64 [Be]Feat: #61 거래신청 및 수락/거절 기능 구현
  Backend/trade/src/main/java/marchtue/reuse/trade/application/dto/request/CreateProposalRequest.java
  Backend/trade/src/main/java/marchtue/reuse/trade/application/dto/response/AcceptProposalResponse.java
  Backend/trade/src/main/java/marchtue/reuse/trade/application/dto/response/CreateProposalResponse.java
  Backend/trade/src/main/java/marchtue/reuse/trade/application/service/PostService.java
  Backend/trade/src/main/java/marchtue/reuse/trade/application/service/ProposalService.java
  Backend/trade/src/main/java/marchtue/reuse/trade/domain/model/Post.java
  Backend/trade/src/main/java/marchtue/reuse/trade/domain/model/Proposal.java
  Backend/trade/src/main/java/marchtue/reuse/trade/domain/model/Trade.java
  Backend/trade/src/main/java/marchtue/reuse/trade/domain/repository/ProposalRepository.java
  Backend/trade/src/main/java/marchtue/reuse/trade/domain/repository/TradeRepository.java
  Backend/trade/src/main/java/marchtue/reuse/trade/exception/ErrorCode.java
  Backend/trade/src/main/java/marchtue/reuse/trade/presentation/ProposalController.java
Labels: Feat, BE

#65 [BC]Feat #63: 에스크로 컨트랙트 구현
  BlockChain/contracts/Escrow.sol
Labels: BC
