Repository MarchTue/ReUse, pull requests merged in 2025-06, with the labels that each got.

#11 [All]Docs #10: update proposal document
  docs/architecture.png
  docs/erd.png
  docs/proposal.md
Labels: documentation

#13 [Feat] User service 기본 기능 구현
  user/.gitattributes
  user/.gitignore
  user/build.gradle
  user/gradle/wrapper/gradle-wrapper.jar
  user/gradle/wrapper/gradle-wrapper.properties
  user/gradlew
  user/gradlew.bat
  user/settings.gradle
  user/src/main/java/marchtue/reuse/user/UserApplication.java
  user/src/main/java/marchtue/reuse/user/application/dto/request/AccountInfo.java
  user/src/main/java/marchtue/reuse/user/application/dto/request/CheckUserRequest.java
  user/src/main/java/marchtue/reuse/user/application/dto/request/NicknameCheckRequest.java
  user/src/main/java/marchtue/reuse/user/application/dto/request/UserAddInfoRequest.java
  user/src/main/java/marchtue/reuse/user/application/dto/request/UserCheckRequest.java
  user/src/main/java/marchtue/reuse/user/application/dto/request/WalletInfo.java
  user/src/main/java/marchtue/reuse/user/application/service/UserService.java
  user/src/main/java/marchtue/reuse/user/domain/enums/BankEnum.java
  user/src/main/java/marchtue/reuse/user/domain/enums/DidTypeEnum.java
  user/src/main/java/marchtue/reuse/user/domain/enums/EWalletPlatformEnum.java
  user/src/main/java/marchtue/reuse/user/domain/enums/EWalletTypeEnum.java
  user/src/main/java/marchtue/reuse/user/domain/enums/UserRoleEnum.java
  user/src/main/java/marchtue/reuse/user/domain/model/Credential.java
  user/src/main/java/marchtue/reuse/user/domain/model/RecentWord.java
  user/src/main/java/marchtue/reuse/user/domain/model/User.java
  user/src/main/java/marchtue/reuse/user/domain/model/UserRating.java
  user/src/main/java/marchtue/reuse/user/domain/model/Wallet.java
  user/src/main/java/marchtue/reuse/user/domain/repository/CredentialRepository.java
  user/src/main/java/marchtue/reuse/user/domain/repository/RecentWordRepository.java
  user/src/main/java/marchtue/reuse/user/domain/repository/UserRatingRepository.java
  user/src/main/java/marchtue/reuse/user/domain/repository/UserRepository.java
  user/src/main/java/marchtue/reuse/user/domain/repository/WalletRepository.java
  user/src/main/java/marchtue/reuse/user/exception/BusinessException.java
  user/src/main/java/marchtue/reuse/user/exception/ErrorCode.java
  user/src/main/java/marchtue/reuse/user/exception/GlobalExceptionHandler.java
  user/src/main/java/marchtue/reuse/user/global/common/BaseEntity.java
  user/src/main/java/marchtue/reuse/user/global/common/BaseEntityNonUpdated.java
  user/src/main/java/marchtue/reuse/user/global/dto/ApiResponse.java
  user/src/main/java/marchtue/reuse/user/global/dto/ErrorResponse.java
  user/src/main/java/marchtue/reuse/user/global/dto/PaginatedResponse.java
  user/src/main/java/marchtue/reuse/user/global/util/BannedWordLoader.java
  user/src/main/java/marchtue/reuse/user/global/util/NicknameFilter.java
  user/src/main/java/marchtue/reuse/user/global/util/RequestUtil.java
  user/src/main/java/marchtue/reuse/user/infrastructure/JpaCredentialRepository.java
  user/src/main/java/marchtue/reuse/user/infrastructure/JpaRecentWordRepository.java
  user/src/main/java/marchtue/reuse/user/infrastructure/JpaUserRatingRepository.java
  user/src/main/java/marchtue/reuse/user/infrastructure/JpaUserRepository.java
  user/src/main/java/marchtue/reuse/user/infrastructure/JpaWalletRepository.java
  user/src/main/java/marchtue/reuse/user/presentation/UserController.java
  user/src/main/resources/banned-words.json
  user/src/test/java/marchtue/reuse/user/UserApplicationTests.java
  user/src/test/java/marchtue/reuse/user/userServiceTest/CheckNicknameTest.java
  user/src/test/java/marchtue/reuse/user/userServiceTest/RegisterUserTest.java
Labels: Feat, BE

#17 Fe/feat/#16 default components
  reuse-app/doc/version_0.1.md
  reuse-app/package.json
  reuse-app/public/manifest.json
  reuse-app/src/app/globals.css
  reuse-app/src/app/layout.tsx
  reuse-app/src/components/theme-provider.tsx
  reuse-app/src/components/ui/navtive-card.tsx
  reuse-app/tailwind.config.ts
Labels: Feat

#31 [BE] Fix #30: user, auth 수정
  Backend/auth/src/main/java/marchtue/reuse/auth/application/client/UserClient.java
  Backend/auth/src/main/java/marchtue/reuse/auth/application/client/UserClientImpl.java
  Backend/auth/src/main/java/marchtue/reuse/auth/application/dto/request/DidCheckRequest.java
  Backend/auth/src/main/java/marchtue/reuse/auth/application/service/AuthService.java
  Backend/db/init.sql
  Backend/trade/src/main/java/marchtue/reuse/trade/global/common/BaseEntity.java
  Backend/user/src/main/java/marchtue/reuse/user/application/dto/request/DidCheckRequest.java
  Backend/user/src/main/java/marchtue/reuse/user/application/service/UserService.java
  Backend/user/src/main/java/marchtue/reuse/user/domain/model/Credential.java
  Backend/user/src/main/java/marchtue/reuse/user/domain/model/User.java
  Backend/user/src/main/java/marchtue/reuse/user/domain/model/UserRating.java
  Backend/user/src/main/java/marchtue/reuse/user/domain/repository/CredentialRepository.java
  Backend/user/src/main/java/marchtue/reuse/user/domain/repository/UserRepository.java
  Backend/user/src/main/java/marchtue/reuse/user/exception/ErrorCode.java
  Backend/user/src/main/java/marchtue/reuse/user/global/common/BaseEntity.java
  Backend/user/src/main/java/marchtue/reuse/user/global/common/BaseEntityNonUpdated.java
  Backend/user/src/main/java/marchtue/reuse/user/global/util/RequestUtil.java
  Backend/user/src/main/java/marchtue/reuse/user/presentation/UserInternalController.java
Labels: bug, BE
